"""Agregar tabla Chat y relacionar con ChatMessage y User

Revision ID: 408fc99730e4
Revises: 446501d81cb7
Create Date: 2024-10-07 20:59:36.069335

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = '408fc99730e4'
down_revision = '446501d81cb7'
branch_labels = None
depends_on = None


def upgrade():
       # ### commands auto generated by Alembic - please adjust! ###
       op.create_table(
           'chat', sa.Column('id', sa.Integer(), nullable=False),
           sa.Column('user_id', sa.Integer(), nullable=False),
           sa.Column('title', sa.String(length=100), nullable=True),
           sa.Column('created_at', sa.DateTime(), nullable=True),
           sa.Column('updated_at', sa.DateTime(), nullable=True),
           sa.ForeignKeyConstraint(
               ['user_id'],
               ['user.id'],
           ), sa.PrimaryKeyConstraint('id'))
       with op.batch_alter_table('chat_message', schema=None) as batch_op:
              batch_op.add_column(
                  sa.Column('chat_id', sa.Integer(), nullable=False))
              batch_op.alter_column('timestamp',
                                    existing_type=postgresql.TIMESTAMP(),
                                    nullable=True)
              batch_op.alter_column('is_user',
                                    existing_type=sa.BOOLEAN(),
                                    nullable=True)
              batch_op.create_index(batch_op.f('ix_chat_message_timestamp'),
                                    ['timestamp'],
                                    unique=False)
              batch_op.create_foreign_key(None, 'chat', ['chat_id'], ['id'])

       with op.batch_alter_table('user', schema=None) as batch_op:
              batch_op.alter_column('password_hash',
                                    existing_type=sa.VARCHAR(length=255),
                                    type_=sa.String(length=512),
                                    nullable=True)
              batch_op.alter_column('is_admin',
                                    existing_type=sa.BOOLEAN(),
                                    nullable=True,
                                    existing_server_default=sa.text('false'))
       # Asignar 'chat_id' a los registros existentes
       bind = op.get_bind()
       connection = bind

       # Crear un chat por cada usuario (Chat por defecto)
       connection.execute(
           text("""
               INSERT INTO chat (user_id, title, created_at, updated_at)
               SELECT id, 'Chat por defecto', NOW(), NOW()
               FROM "user"
           """))

       # Asignar 'chat_id' a 'chat_message' basándose en el 'user_id'
       connection.execute(
           text("""
               UPDATE chat_message
               SET chat_id = chat.id
               FROM chat
               WHERE chat.user_id = chat_message.user_id
           """))

       # Ahora, establecer 'chat_id' como NOT NULL
       with op.batch_alter_table('chat_message', schema=None) as batch_op:
              batch_op.alter_column('chat_id',
                                    existing_type=sa.Integer(),
                                    nullable=False)

       # connection.close()

       # ### end Alembic commands ###


def downgrade():
       # ### commands auto generated by Alembic - please adjust! ###
       with op.batch_alter_table('user', schema=None) as batch_op:
              batch_op.alter_column('is_admin',
                                    existing_type=sa.BOOLEAN(),
                                    nullable=False,
                                    existing_server_default=sa.text('false'))
              batch_op.alter_column('password_hash',
                                    existing_type=sa.String(length=128),
                                    type_=sa.VARCHAR(length=255),
                                    nullable=False)

       with op.batch_alter_table('chat_message', schema=None) as batch_op:
              batch_op.drop_constraint(None, type_='foreignkey')
              batch_op.drop_index(batch_op.f('ix_chat_message_timestamp'))
              batch_op.alter_column('is_user',
                                    existing_type=sa.BOOLEAN(),
                                    nullable=False)
              batch_op.alter_column('timestamp',
                                    existing_type=postgresql.TIMESTAMP(),
                                    nullable=False)
              batch_op.drop_column('chat_id')

       op.drop_table('chat')
       # ### end Alembic commands ###
